### PR TITLE
RouteResponse usage

### LINKED ISSUE #135: Support RouteResponse usage
After [refactoring RouteResponse usage](https://github.com/mapbox/mapbox-navigation-ios/pull/3182) instead of bare Route object, we need to update examples code to reflect that change.

### PR DESCRIPTION
**Pull request by Udumft**
Resolves #135 
Bumped Navigation SDK to beta.21

### CODE REVIEW

**Comment by S2Ler** [comment]
@Udumft Hey, I wonder what `vk-135-route-response` means in the beginning of the each commit. It pollutes the commit message in my opinion. Is it possible to use this tag in description at least if it is valuable?

**Comment by Udumft** [comment]
It's pattern is <author's_initials>-<ticket_#>-<human_readable_tag>. I find it convenient to track changes related to a specific ticket after the PR is merged. 
You can use history search to find specific author or ticket changes.
Imagine if you are investigating unit tests changes. Without such commit message there would be a dozen of "unit tests update" commits, but adding ticket ID gives you context to understand what this particular change is for and author name to ask extra questions if needed.

**Comment by S2Ler** [comment]
Doesn't look that it is standardised pattern in the team, makes sense to discuss. Also, such information is easy to hide in the description instead of the title.

**Comment by Udumft** [comment]
Let's follow up commit messaging talk in `discussions`

**Pull request merged**
